Move JsonConvert into apartment.json
av1m/Apartments pull request #27
Opened 2020-05-10 08:24 UTC by GabG02

Déplacer JsonConvert de utils vers apartment.json
fix https://github.com/av1m/Apartments/issues/21

2020-05-11 07:46 UTC, MorganeFt requested changes

2020-05-11 07:46 UTC, MorganeFt commented on src/test/java/io/github/oliviercailloux/y2018/apartments/apartment/json/JsonConvertTest.java
> +import io.github.oliviercailloux.y2018.apartments.apartment.json.JsonConvert;
Cet import n'est pas nécessaire et doit être supprimé. Le package de test portant le même nom que celui contenant la classe JsonConvert, celui-ci n'a pas besoin d'être importé. (Organize Imports dans Eclipse)

2020-05-13 16:18 UTC, GabG02 commented on src/test/java/io/github/oliviercailloux/y2018/apartments/apartment/json/JsonConvertTest.java
> +import io.github.oliviercailloux.y2018.apartments.apartment.json.JsonConvert;
fix

2020-05-13 16:28 UTC, MorganeFt approved these changes

2020-05-13 16:30 UTC, merged