Unit test improvement and creation of the apartment.xml package
av1m/Apartments pull request #31
Opened 2020-05-26 00:12 UTC by av1m

At first, we wanted to modify a test class that declared a hand and no tests. This was not necessary and could lead to misunderstanding when reading the documentation. see [here](https://github.com/av1m/Apartments/blob/d7a028ec4184fca5bc5d891de3ed6c94da742eef/Doc/overview.adoc#readtwoapartmentstest)

Then we noticed that we have centralized the json functions in `apartment.json` and we thought that it would be wise to do the same for XML, so we create a new package `apartment.xml`

It is important to note that this PR answers two things (we judged that it was useless to make two PR because it is a lot of refactoring) : 

* Improvement of the `ReadApartmentsXMLFormatTest` class as mentioned in the first paragraph
* Migration of the `readapartments` and `toxmlproperties` package into the `apartment.xml` package

**Please note that apart from the `ReadApartmentsXMLFormatTest.java` file, the files have not been modified (except for imports and paths). Thus, the second goal of this PR is not to improve these other files but to improve the organization of packages**

In addition, the documentation (in `.adoc` format) has been updated

2020-05-26 11:25 UTC, MorganeFt requested changes
Dans un souci de lisibilité de la PR, nous avons décidé de ne pas prendre en compte les remarques de BP format. De plus, lors de cette itération, nous allons implémenter le google-java-format qui résoudra ce genre de problèmes.

De même, les classes toxmlproperties et ReadApartmentsXMLFormat pourraient être optimisée dans une prochaine PR.

2020-05-26 11:25 UTC, MorganeFt commented on src/test/java/io/github/oliviercailloux/y2018/apartments/apartment/xml/ToXmlPropertiesTest.java
> +import io.github.oliviercailloux.y2018.apartments.apartment.xml.XMLProperties;
Organize imports

2020-05-26 14:06 UTC, av1m commented on src/test/java/io/github/oliviercailloux/y2018/apartments/apartment/xml/ToXmlPropertiesTest.java
> +import io.github.oliviercailloux.y2018.apartments.apartment.xml.XMLProperties;
Resolve in 599c690cd2e0d2b0bceee3a241d29bd9989a7674

2020-05-26 14:22 UTC, av1m commented
Les imports seront également ordonnés à l'aide de google-java-format.

Les imports inutilisés ont été supprimés.

2020-05-26 16:05 UTC, MorganeFt approved these changes

2020-05-29 08:54 UTC, oliviercailloux approved these changes

2020-05-31 08:19 UTC, merged