Fix #47 : Add cache for github actions
av1m/Apartments pull request #48
Opened 2020-06-13 22:36 UTC by av1m

Here is a way to save maven dependencies in the cache.

The [example](https://github.com/actions/cache/blob/master/examples.md#java---maven) was found on the official documentation of the [actions/cache](https://github.com/actions/cache/) action

_Documentation on the general cache of github actions is available [here](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows)._

2020-06-14 00:39 UTC, MorganeFt approved these changes

2020-06-15 21:12 UTC, clemencecousin approved these changes

2020-06-16 18:35 UTC, oliviercailloux requested changes
On dirait d’après la page https://github.com/av1m/Apartments/pull/48/checks?check_run_id=768908934 que Maven télécharge toujours tous ses plug-ins. Est-ce parce que le cache n’avait pas encore pris effet ? Pouvez-vous dans ce cas refaire un push pour illustrer le résultat ?

2020-06-16 18:41 UTC, av1m commented
J'avais fais le test dans un repository de test.
Voici le résultat après push https://github.com/av1m/Apartments/pull/48/checks?check_run_id=777732013

2020-06-17 06:52 UTC, oliviercailloux requested changes
Le système de hash + restore-keys me semble inutilement compliqué. Indiquez-moi quel avantage vous y voyez, ou simplifiez-le, SVP. De même, la variable runner-os n’est pas nécessaire ici.

2020-06-17 07:19 UTC, oliviercailloux approved these changes
Erreur de ma part, le système de hash + restore-keys est indispensable.

Je maintiens que runner-os est inutile à mon avis. OPT.

2020-06-17 09:44 UTC, av1m commented
Utiliser le système de `hashfiles` avec la `key` est effectivement indispensable.

`runner.os` retourne ici "Linux"
Il peux être retiré ici vu que l'on utilise que Ubuntu.

La clé à actuellement la forme:
**Linux-maven-{hash}**

En retirant `runner.os` elle aura la forme:
**maven-{hash}**

Il est important de garder le préfixe maven car dans le cas ou il n'y a pas de résultat sur une branche, l'action `cache` peut rechercher dans les branches parents à l'aide du pattern donné (ici `maven-`). En ce sens `restore-keys` est optionnel mais permet à ce que l'action `cache` recherche séquentiellement tous les caches qui correspondent à la liste des `restore-keys`.
Nous pouvons ainsi la supprimer mais elle reste utile dans le cas ou une branche ne dispose pas du cache, par exemple.

2020-06-17 09:50 UTC, av1m commented
On peut également voir que en ayant enlevé `runner.os`, la `key` du dernier commit 0ba53f85f8faac980f5475555492ca4f558c0f26 n'est plus la même (car le `Linux-` a été enlevé)

Ainsi, l'action `cache` a retéléchargé les dépendances, voir [check commit 0ba53f8](https://github.com/av1m/Apartments/pull/48/checks?check_run_id=779865653)

2020-06-17 11:39 UTC, merged