Changed name of LinearAVF method setWeight to withWeight
av1m/Apartments pull request #57
Opened 2020-06-19 12:10 UTC by EtienneCartier

Fixing issue #50

2020-06-19 12:47 UTC, clemencecousin approved these changes
Juste du renommage de variables, donc OK. Pas de conflits avec les autres PR faites sur ces fichiers après vérification.

2020-06-19 15:22 UTC, oliviercailloux requested changes
setWeight est un nom correct sur un builder. withWeight serait le nom approprié sur un objet qui ne serait pas modifié par l’appel.

2020-06-22 18:41 UTC, av1m commented
On attend de merge #56 et #58 car on aura pas mal de changement sur `Profile` et `LinearAVF`

2020-06-26 15:24 UTC, av1m commented
Comme mentionné dans mon précédent commentaire, et oliviercailloux [a demandé](https://github.com/av1m/Apartments/pull/57#pullrequestreview-434161618):
Toutes les fonctions qui retournent un objet (ex: `public LinearAVF nomFonction()`) et qui ont comme nom `setWeight`, ont été remplacés par `withWeight`

Les fonctions des Builders n'ont pas été changées.

2020-06-26 17:35 UTC, oliviercailloux approved these changes

2020-06-28 08:09 UTC, merged